# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/wikto/studia/zybo_pynq/zybo_pynq.srcs/sources_1/bd/zybo_taylor/ip/zybo_taylor_processing_system7_0_0/zybo_taylor_processing_system7_0_0.xci
# IP: The module: 'zybo_taylor_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wikto/studia/zybo_pynq/zybo_pynq.gen/sources_1/bd/zybo_taylor/ip/zybo_taylor_processing_system7_0_0/zybo_taylor_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_taylor_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/wikto/studia/zybo_pynq/zybo_pynq.srcs/sources_1/bd/zybo_taylor/ip/zybo_taylor_processing_system7_0_0/zybo_taylor_processing_system7_0_0.xci
# IP: The module: 'zybo_taylor_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wikto/studia/zybo_pynq/zybo_pynq.gen/sources_1/bd/zybo_taylor/ip/zybo_taylor_processing_system7_0_0/zybo_taylor_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_taylor_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
