# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_taylor/zybo_taylor.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_taylor || ORIG_REF_NAME==zybo_taylor} -quiet] -quiet

# IP: bd/zybo_taylor/ip/zybo_taylor_processing_system7_0_0/zybo_taylor_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_taylor_processing_system7_0_0 || ORIG_REF_NAME==zybo_taylor_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_taylor/ip/zybo_taylor_axi_interconnect_0_0/zybo_taylor_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_taylor_axi_interconnect_0_0 || ORIG_REF_NAME==zybo_taylor_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zybo_taylor/ip/zybo_taylor_rst_ps7_0_50M_0/zybo_taylor_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_taylor_rst_ps7_0_50M_0 || ORIG_REF_NAME==zybo_taylor_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zybo_taylor/ip/zybo_taylor_taylor_ip_0_1/zybo_taylor_taylor_ip_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_taylor_taylor_ip_0_1 || ORIG_REF_NAME==zybo_taylor_taylor_ip_0_1} -quiet] -quiet

# IP: bd/zybo_taylor/ip/zybo_taylor_auto_pc_0/zybo_taylor_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_taylor_auto_pc_0 || ORIG_REF_NAME==zybo_taylor_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/wikto/studia/zybo_pynq/zybo_pynq.gen/sources_1/bd/zybo_taylor/zybo_taylor_ooc.xdc
