webtalk_init -webtalk_dir C:/Users/Public/Documents/JR_PROJECT/FPGA_taylor_aproximation/src/jrwp/jrwp.sim/sim_1/behav/xsim/xsim.dir/taylor_beh_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun  1 12:33:38 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212363321_0_0_928" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8aa29c30-f6bf-4862-99a5-3bb61d9678d0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "982c4ab2a7d547b9a2250c9cdc899e6d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1000010 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6596_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2623967396 -regid "212363321_0_0_928" -xml C:/Users/Public/Documents/JR_PROJECT/FPGA_taylor_aproximation/src/jrwp/jrwp.sim/sim_1/behav/xsim/xsim.dir/taylor_beh_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Public/Documents/JR_PROJECT/FPGA_taylor_aproximation/src/jrwp/jrwp.sim/sim_1/behav/xsim/xsim.dir/taylor_beh_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Public/Documents/JR_PROJECT/FPGA_taylor_aproximation/src/jrwp/jrwp.sim/sim_1/behav/xsim/xsim.dir/taylor_beh_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
